version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-nonprod
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - app-bundle:/usr/local/bundle
  postgres:
    image: postgres:10-alpine
    environment:
      POSTGRES_PASSWORD: secret
    ports:
      - 5430:5432
    volumes:
     - postgres:/var/lib/postgresql/data
  redis:
    image: redis:alpine
    volumes:
    - redis:/data


volumes:
  app-bundle:
  redis:
  postgres:
