default: &default
  adapter: postgresql
  encoding: unicode
  locale: pt_BR.UTF-8
  timeout: 5000
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  host: <%= ENV.fetch('DB_HOST') %>
  port: <%= ENV.fetch('DB_PORT') { 5432 } %>
  username: <%= ENV.fetch('DB_USERNAME') %>
  password: <%= ENV.fetch('DB_PASSWORD') %>

development:
  <<: *default
  database: <%= ENV['APP_NAME'] %>_development

test:
  <<: *default
  database: <%= ENV['APP_NAME'] %>_test<%= ENV['TEST_ENV_NUMBER'] %>

production:
  <<: *default
  database: <%= ENV['APP_NAME'] %>_production
